# Generated by Django 2.2.11 on 2020-04-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='community_centers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=255, verbose_name='Address')),
                ('lat', models.CharField(max_length=255, verbose_name='lat')),
                ('lon', models.CharField(max_length=255, verbose_name='lon')),
                ('Name', models.CharField(max_length=255, verbose_name='Name')),
                ('neighborhood', models.CharField(max_length=255, verbose_name='neighborhood')),
            ],
            options={
                'db_table': 'community_centers',
            },
        ),
        migrations.CreateModel(
            name='dog_gardens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=255, verbose_name='lat')),
                ('lon', models.CharField(max_length=255, verbose_name='lon')),
                ('Name', models.CharField(max_length=255, verbose_name='Name')),
                ('SHAPE_Area', models.CharField(max_length=255, verbose_name='SHAPE_Area')),
                ('SHAPE_Length', models.CharField(max_length=255, verbose_name='SHAPE_Length')),
            ],
            options={
                'db_table': 'dog_gardens',
            },
        ),
        migrations.CreateModel(
            name='elderly_social_club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=255, verbose_name='Address')),
                ('lat', models.CharField(max_length=255, verbose_name='lat')),
                ('lon', models.CharField(max_length=255, verbose_name='lon')),
                ('Name', models.CharField(max_length=255, verbose_name='Name')),
                ('Type', models.CharField(max_length=255, verbose_name='type')),
            ],
            options={
                'db_table': 'elderly_social_club',
            },
        ),
        migrations.CreateModel(
            name='playgrounds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrousel', models.IntegerField(verbose_name='carrousel')),
                ('combined1', models.IntegerField(verbose_name='combined1')),
                ('combined2', models.IntegerField(verbose_name='combined2')),
                ('combined3', models.IntegerField(verbose_name='combined3')),
                ('omega', models.IntegerField(verbose_name='omega')),
                ('roserose', models.IntegerField(verbose_name='roserose')),
                ('slid', models.IntegerField(verbose_name='slid')),
                ('SpecialCom', models.IntegerField(verbose_name='SpecialCom')),
                ('spring', models.IntegerField(verbose_name='spring')),
                ('Swing', models.IntegerField(verbose_name='Swing')),
                ('other', models.CharField(max_length=255, verbose_name='other')),
                ('shadowing', models.CharField(max_length=255, verbose_name='shadowing')),
                ('surface', models.CharField(max_length=255, verbose_name='surface')),
                ('lat', models.CharField(max_length=255, verbose_name='lat')),
                ('lon', models.CharField(max_length=255, verbose_name='lon')),
                ('Name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'db_table': 'playgrounds',
            },
        ),
        migrations.CreateModel(
            name='sport_facilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=255, verbose_name='shadowing')),
                ('Name', models.CharField(max_length=255, verbose_name='Name')),
                ('street', models.CharField(max_length=255, verbose_name='street')),
                ('HouseNumber', models.CharField(max_length=255, verbose_name='HouseNumber')),
                ('neighborhood', models.CharField(max_length=255, verbose_name='neighborhood')),
                ('Operator', models.CharField(max_length=255, verbose_name='Operator')),
                ('Seats', models.IntegerField(verbose_name='Seats')),
                ('Activity', models.CharField(max_length=255, verbose_name='Activity')),
                ('fencing', models.CharField(max_length=255, verbose_name='fencing')),
                ('lighting', models.CharField(max_length=255, verbose_name='lighting')),
                ('handicapped', models.CharField(max_length=255, verbose_name='handicapped')),
                ('condition', models.CharField(max_length=255, verbose_name='condition')),
                ('Owner', models.CharField(max_length=255, verbose_name='Owner')),
                ('ForSchool', models.CharField(max_length=255, verbose_name='ForSchool')),
                ('association', models.CharField(max_length=255, verbose_name='association')),
                ('SportType', models.CharField(max_length=255, verbose_name='SportType')),
                ('lat', models.CharField(max_length=255, verbose_name='lat')),
                ('lon', models.CharField(max_length=255, verbose_name='lon')),
            ],
            options={
                'db_table': 'sport_facilities',
            },
        ),
        migrations.CreateModel(
            name='urban_nature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MainFeature', models.CharField(max_length=255, verbose_name='MainFeature')),
                ('lat', models.CharField(max_length=255, verbose_name='lat')),
                ('lon', models.CharField(max_length=255, verbose_name='lon')),
            ],
            options={
                'db_table': 'urban_nature',
            },
        ),
    ]
