# Generated by Django 2.2.11 on 2020-04-20 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20200421_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elderly_social_club',
            old_name='Name',
            new_name='name',
        ),
    ]
