# Generated by Django 2.2.11 on 2020-04-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_auto_20200422_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community_centers',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='dog_gardens',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='elderly_social_club',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='playgrounds',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='sport_facilities',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
    ]
