# Generated by Django 2.2.11 on 2020-04-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_auto_20200423_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport_facilities',
            name='HouseNumber',
        ),
        migrations.RemoveField(
            model_name='sport_facilities',
            name='street',
        ),
        migrations.AddField(
            model_name='sport_facilities',
            name='address',
            field=models.CharField(default='test', max_length=255, verbose_name='address'),
            preserve_default=False,
        ),
    ]
