# Generated by Django 2.2.11 on 2020-04-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_auto_20200429_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog_gardens',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='elderly_social_club',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playgrounds',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sport_facilities',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='urban_nature',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
