pipeline {
    agent {
		docker {
			image 'leorrose13/b7fun:latest'
		}
	}
	triggers {
        githubPush()
    }
	options {
		skipDefaultCheckout(true)
        timeout(time: 60, unit: 'MINUTES')
    }
    stages {
		stage('Repository Fetch') {
			steps {
				checkout scm
			}
		}
        stage('Application Setup') {
            steps {
				withEnv(["HOME=${env.WORKSPACE}"]) {
					sh 'python3 -m pip install --upgrade pip --user'
					dir("B7FunDjango") {
						sh 'python3 manage.py makemigrations'
						sh 'python3 manage.py migrate'
					}
				}
            }
        }
		stage('Run Unit Tests') {
            steps {
				dir("B7FunDjango") {
					withEnv(["HOME=${env.WORKSPACE}"]) {
						sh "python3 -m coverage run manage.py test --tag=unit-test"
					}
				}
			}
        }
		
		stage('Run Integration Tests') {
            steps {
				dir("B7FunDjango") {
					withEnv(["HOME=${env.WORKSPACE}"]) {
						sh "python3 -m coverage run -a manage.py test --tag=integration-test"
					}
				}
			}
        }
		
		stage('Metric 1 - unit test coverage') {
			steps {
				dir("B7FunDjango") {
					withEnv(["HOME=${env.WORKSPACE}"]) {
						sh 'python3 -m coverage xml -o ./reports/coverage.xml'
						sh 'python3 -m coverage report --fail-under=80'
					}
				}
			}
		}
		
		stage('Metric 2 - pylint python code convention') {
			steps {
				dir("B7FunDjango") {
					withEnv(["HOME=${env.WORKSPACE}"]) {
						sh 'python3 -m pylint B7FunDjango accounts feed postsFeed Profile reviews'
					}
				}
			}
		}
		
		stage('Metric 3 - Test Trend Chart') {
			steps {
				dir("B7FunDjango") {
					junit allowEmptyResults: true, testResults: 'reports/unittest.xml'
				}
			}
		}
		
    }
	post {
		failure{
			mail to: 'B7FunService@gmail.com',
			subject: "Failed: Job '${env.JOB_NAME}' ['${env.BUILD_NUMBER}']",
			body: 'Failed: Job ${env.JOB_NAME} [${env.BUILD_NUMBER}]: Check console output at ${env.BUILD_URL} ${env.JOB_NAME} [${env.BUILD_NUMBER}]'
		}
		success{
			mail to: 'B7FunService@gmail.com',
			subject: "SUCCESS: Job '${env.JOB_NAME}' ['${env.BUILD_NUMBER}']",
			body: "SUCCESS: Job '${env.JOB_NAME}' ['${env.BUILD_NUMBER}']: Check console output at '${env.BUILD_URL}' '${env.JOB_NAME}' ['${env.BUILD_NUMBER}']"
		}
		always{
			deleteDir()
		}
	}
}