# Generated by Django 2.2.11 on 2020-05-01 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('review_content', models.TextField(max_length=500, verbose_name='review_content')),
                ('sender_email', models.EmailField(max_length=60, verbose_name='sender_email')),
                ('sender_user_name', models.CharField(max_length=30, verbose_name='sender_user_name')),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='rating')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
    ]
