# Generated by Django 2.2.11 on 2020-05-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
