# Generated by Django 2.2.11 on 2020-05-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emails',
            name='content',
        ),
        migrations.AddField(
            model_name='emails',
            name='content1',
            field=models.CharField(default='hgh', max_length=500, verbose_name='content'),
            preserve_default=False,
        ),
    ]
