# Generated by Django 2.2.11 on 2020-04-06 14:33

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200406_1353'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.MyUserManager()),
            ],
        ),
    ]
