# Generated by Django 2.2.11 on 2020-05-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200523_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=60, unique=True, verbose_name='user email')),
                ('login_month', models.IntegerField()),
                ('login_year', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'User logins',
                'db_table': 'user logins',
            },
        ),
    ]
