# Generated by Django 2.2.11 on 2020-05-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_logins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logins',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='logins',
            name='user_email',
            field=models.EmailField(max_length=60, verbose_name='user email'),
        ),
    ]
