# Generated by Django 2.2.11 on 2020-04-15 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postsFeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postfeed',
            options={'verbose_name_plural': 'Post_Feed'},
        ),
    ]
