# Generated by Django 2.2.11 on 2020-04-15 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postsFeed', '0002_auto_20200415_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postfeed',
            options={'verbose_name_plural': 'Post Feed'},
        ),
    ]
