# Generated by Django 2.2.11 on 2020-05-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Time sent')),
                ('message', models.TextField(verbose_name='message')),
                ('sender_email', models.EmailField(max_length=60, verbose_name='sender email')),
                ('chat_room_type', models.CharField(max_length=30, verbose_name='Chat room type')),
                ('chat_room_id', models.IntegerField(verbose_name='Chat room id')),
            ],
            options={
                'verbose_name_plural': 'Chat Messages',
                'db_table': 'Chat Messages',
            },
        ),
    ]
