# Generated by Django 2.2.11 on 2020-05-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='sender_email',
            field=models.EmailField(max_length=60, verbose_name='sender email'),
        ),
    ]
