# Generated by Django 2.2.11 on 2020-05-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200520_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='chat_room_type',
            field=models.CharField(default=1, max_length=30, verbose_name='Chat room type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='chat_room_id',
            field=models.IntegerField(verbose_name='Chat room id'),
        ),
        migrations.AlterModelTable(
            name='chatmessage',
            table='Chat Messages',
        ),
    ]
